apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-predictor-frontend
  namespace: pl-predictor
  labels:
    app: pl-predictor-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pl-predictor-frontend
  template:
    metadata:
      labels:
        app: pl-predictor-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/your-username/pl-predictor/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend-service:8000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pl-predictor
spec:
  selector:
    app: pl-predictor-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
